### PR TITLE
Bump version to 0.1.1

### PR DESCRIPTION
**Pull request by belldandyxtq**

### CODE REVIEW

**Comment by kuenishi** [comment]
Master test is still failing. It must be fixed.

```
$ pytest tests
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.6.8, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: /home/kota/src/chainerio, inifile: setup.cfg
collected 91 items / 2 errors / 89 selected                                                                                                                             

================================================================================ ERRORS =================================================================================
_____________________________________________________ ERROR collecting tests/filesystem_tests/test_hdfs_handler.py ______________________________________________________
tests/filesystem_tests/test_hdfs_handler.py:4: in <module>
    from chainerio.filesystems.hdfs import _parse_principal_name_from_klist
E   ImportError: cannot import name '_parse_principal_name_from_klist'
_____________________________________________________ ERROR collecting tests/filesystem_tests/test_hdfs_handler.py ______________________________________________________
ImportError while importing test module '/home/kota/src/chainerio/tests/filesystem_tests/test_hdfs_handler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/filesystem_tests/test_hdfs_handler.py:4: in <module>
    from chainerio.filesystems.hdfs import _parse_principal_name_from_klist
E   ImportError: cannot import name '_parse_principal_name_from_klist'
=========================================================================== warnings summary ============================================================================
/home/kota/.local/lib/python3.6/site-packages/_pytest/mark/structures.py:324
  /home/kota/.local/lib/python3.6/site-packages/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.gpu - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 1 warnings, 2 error in 1.06s ======================================================================
$ git log -1
commit 14e51bd70fb0b117914ede822a1db47d4d80bd28 (HEAD -> master, origin/master, origin/HEAD)
Merge: ca79de9 9d07cef
Author: UENISHI Kota <kuenishi@users.noreply.github.com>
Date:   Thu Dec 19 14:10:35 2019 +0900

    Merge pull request #97 from chainer/bugfix_krb_keytab
    
    Bugfix: get correct principal name when keytab is given

```

**Comment by belldandyxtq** [comment]
Sorry, I cannot reproduce the error @kuenishi 

```
tianqi:chainerio$ git log -1
commit 14e51bd70fb0b117914ede822a1db47d4d80bd28
Merge: ca79de9 9d07cef
Author: UENISHI Kota <kuenishi@users.noreply.github.com>
Date:   Thu Dec 19 14:10:35 2019 +0900

    Merge pull request #97 from chainer/bugfix_krb_keytab

    Bugfix: get correct principal name when keytab is given
tianqi:chainerio$ pytest tests/
===================================== test session starts =====================================
platform linux -- Python 3.6.8, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: tianqi/repository/chainerio, inifile: setup.cfg
collected 107 items

tests/test_context.py ...............                                                   [ 14%]
tests/cache_tests/test_cache.py ................xxxxxxxx................                [ 51%]
tests/cache_tests/test_file_cache.py ...                                                [ 54%]
tests/cache_tests/test_mt.py ..                                                         [ 56%]
tests/chainer_extensions_test/test_snapshot.py sss                                      [ 58%]
tests/container_tests/test_zip_container.py ...............                             [ 72%]
tests/filesystem_tests/test_hdfs_handler.py ................                            [ 87%]
tests/filesystem_tests/test_posix_handler.py .............                              [100%]

====================================== warnings summary =======================================
tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327
  tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.cudnn - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327
  tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.ideep - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327
  tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327
  tianqi/.pyenv/versions/3.6.8/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.gpu - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

tests/container_tests/test_zip_container.py::TestZipHandler::test_nested_zip
  tianqi/repository/chainerio/chainerio/containers/zip.py:56: RuntimeWarning: In Python < 3.7, To support opening nested zip as container, ChainerIO has to read the entire nested zip upon open, which might cause performance or memory issues when the nested zip is huge.
    category=RuntimeWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 96 passed, 3 skipped, 8 xfailed, 5 warnings in 18.93s ====================
```

Can you double check the `ChainerIO` installation?
https://github.com/chainer/chainerio/blob/14e51bd70fb0b117914ede822a1db47d4d80bd28/chainerio/filesystems/hdfs.py#L21

**Comment by kuenishi** [comment]
I re-built my env and had different error, which looks like a test code bug.
```
$ env | grep KRB
$ pytest -s -v tests/filesystem_tests/test_hdfs_handler.py::TestHdfsHandler::test_get_principal_name
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.6.8, pytest-5.1.2, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/kota/src/chainerio, inifile: setup.cfg
collected 1 item                                                                                                                                                        

tests/filesystem_tests/test_hdfs_handler.py::TestHdfsHandler::test_get_principal_name FAILED

=============================================================================== FAILURES ================================================================================
________________________________________________________________ TestHdfsHandler.test_get_principal_name ________________________________________________________________

self = <test_hdfs_handler.TestHdfsHandler testMethod=test_get_principal_name>

    def test_get_principal_name(self):
        ticket_cache_path = "/tmp/krb5cc_{}".format(os.getuid())
        ticket_cache_backup_path = "/tmp/ccbackup_{}".format(getpass.getuser())
    
        # remove the credential cache
        if chainerio.exists(ticket_cache_path):
            chainerio.rename(ticket_cache_path, ticket_cache_backup_path)
        original_ccname = os.environ.get("KRB5CCNAME")
        if original_ccname is not None:
            del os.environ['KRB5CCNAME']
    
        # remove klist
        original_path = os.environ.get('PATH')
        del os.environ['PATH']
    
        # remove keytab
        original_krb5_ktname = os.environ.get('KRB5_KTNAME')
>       del os.environ['KRB5_KTNAME']

tests/filesystem_tests/test_hdfs_handler.py:82:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = environ({'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=...'PYTEST_CURRENT_TEST': 'tests/filesystem_tests/test_hdfs_handler.py::TestHdfsHandler::test_get_principal_name (call)'})
key = 'KRB5_KTNAME'

    def __delitem__(self, key):
        encodedkey = self.encodekey(key)
        self.unsetenv(encodedkey)
        try:
            del self._data[encodedkey]
        except KeyError:
            # raise KeyError with the original key value
>           raise KeyError(key) from None
E           KeyError: 'KRB5_KTNAME'

/usr/lib/python3.6/os.py:685: KeyError
=========================================================================== 1 failed in 0.21s ===========================================================================
```
With `KRB5_KTNAME=''` given to pytest command it passes. Environment variable removal should be done safely.

**Comment by belldandyxtq** [comment]
I see, sorry for the bug

**Comment by kuenishi** [comment]
Please go ahead for release.

**Pull request merged**
